export { watermarkSermon as watermark } from './watermarkSermon'
export { default as tvc } from './tvcSermon'
export { default as prestonwood } from './prestonwoodSermon'
export { default as covenant } from './covenantSermon'
export { default as fellowship } from './fellowshipSermon'
export { default as fbc } from './fbcSermon'
